#!/bin/bash
set -x
TARGET_DIR=flatten/
TARGET_FILE=flatten-doc-${1?Error:name document please}
mkdir -p ${TARGET_DIR}
# Expand to a single file, remove comments
latexpand main.tex > ${TARGET_DIR}/${TARGET_FILE}.tex
# Copy resources
cp main.bbl ${TARGET_DIR}/${TARGET_FILE}.bbl
cp main.bbl diff.bbl
cp iohk.sty ${TARGET_DIR}
cp iohk-share-logo.jpg ${TARGET_DIR}
cp IOHKCoverPage.sty ${TARGET_DIR}
# mkdir -p ${TARGET_DIR}/Figures
# cp -r Figures/ ${TARGET_DIR}/Figures