[book]
authors = ["iquerejeta"]
language = "en"
multilingual = false
src = "src"
title = "IOG Cryptography Handbook"

[output.html]
mathjax-support = true

[preprocessor.katex]
macros = "./macros.txt"

#[preprocessor.graphviz]
#command = "mdbook-graphviz"
#output-to-file = false
