[book]
authors = ["iquerejeta"]
language = "en"
multilingual = false
src = "src"
title = "IOG Cryptography Handbook"

[output.html]
mathjax-support = true

[output.katex]

[preprocessor.katex]
macros = "./macros.txt"
