name: Deploy
on:
  pull_request:
    branches: [ "**" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install mdbook-katex
        uses: baptiste0928/cargo-install@v2
        with:
          crate: mdbook-katex
      - name: Install mdbook-graphviz
        uses: baptiste0928/cargo-install@v2
        with:
          crate: mdbook-graphviz
      - name: Install mdbook
        uses: baptiste0928/cargo-install@v2
        with:
          crate: mdbook
      - name: Deploy GitHub Pages
        run: |
          cd cryptography-handbook
          mdbook build
          mkdir gh-pages
          git worktree add gh-pages
          git config user.name "Deploy from CI"
          git config user.email ""
          cd gh-pages# Delete the ref to avoid keeping history.
          git update-ref -d refs/heads/gh-pages
          rm -rf *
          mv ../book/html/* .
          git add .
          git commit -m "Deploy $GITHUB_SHA to gh-pages"
          git push --force --set-upstream origin gh-pages
